version: '3.3'

services:
  mijncmd_app:
    image: nordyvlas/mijncmd-runtime:1.0.1
    command: >
      /bin/sh -c 'apt-get update && apt-get install -y inotify-tools &&
      mix local.hex --force &&
      mix local.rebar --force &&
      mix deps.get &&
      mix ecto.setup &&
      mix phx.gen.cert mijncmd mijncmd.local 68.183.13.93 &&
      mix phx.server'
    ports:
      - '4000:4000'
      - '4001:4001'
    depends_on:
      - postgres
    working_dir: /app
    environment:
      DB_HOST: postgres
      DB_NAME: mijncmd_dev
      DB_USER: postgres
      DB_PASS: postgres
      HTTPS: 'true'
      VIRTUAL_HOST: &host "${HOST:-localhost}"
      HOST: *host
      GIT_SHA: "0fa5476"
      GIT_AUTHOR: "Nordy Vlasman"
    volumes:
      - ../config:/app/config:ro
      - ../lib:/app/lib

      - ../mix.exs:/app/mix.exs:ro
      - ../mix.lock:/app/mix.lock:ro

      - ../priv/repo:/app/priv/repo:ro
      - ../uploads:/app/uploads

      - mijncmd_app_cert:/app/priv/cert
      - mijncmd_app_deps:/app/deps/
      - mijncmd_app_build:/app/_build/
volumes:
  mijncmd_app_deps: {}
  mijncmd_app_build: {}
  mijncmd_app_cert: {}
  mijncmd_app_static: {}
